// Graphics interception and shader authoring for MWOn12 plugins.
//
// <mwon12/plugin.hpp> gives a plugin one moment per frame: OnPresent, after the
// game has finished drawing. That is the right place to draw *over* the game and
// the wrong place to change how the game itself was drawn — by then it already
// has been.
//
// This header opens the frame up. It attaches VanGFX to the D3D12 device MWOn12
// is rendering the game with, so a plugin sees every draw as it is recorded,
// every pipeline state as it is created, and every resource as it appears:
//
//     #include <mwon12/graphics.hpp>
//
//     mwon12::gfx::Context m_gfx;          // a member, not a local
//
//     void OnDeviceCreated(const MWOn12_DeviceInfo& d) override {
//         if (!m_gfx.Attach(d)) return;
//
//         m_gfx->on_draw([](vangfx::FrameContext&, vangfx::DrawEvent& ev) {
//             if (ev.index_count > 5000) ev.intercept = true;   // skip it
//         });
//     }
//
//     void OnDeviceDestroyed() override { m_gfx.Detach(); }
//
//
// WHAT THIS SEES, AND WHY IT IS THE GAME
//
// The game is a Direct3D 9 program. It never issues a D3D12 command — MWOn12
// translates what it asks for into D3D12 and issues that. So the draws arriving
// here are MWOn12's, one or more per D3D9 draw the game made, against shaders
// MWOn12 generated by translating the game's D3D9 bytecode.
//
// That is a feature rather than a caveat: it is the game's rendering, expressed
// in an API with pipeline state objects, root signatures and DXIL, which is
// what makes it something a modern effect can be attached to at all.
//
// It does mean the vocabulary is MWOn12's. A DrawEvent's shaders are translated
// HLSL, not `world.fx`. To find out which draw is which, the practical route is
// the same one the shader kit describes: dump the shaders, make one of them
// return magenta, and see what turns magenta.
//
//
// WHEN NOT TO USE THIS
//
// For a HUD, an overlay, a graph, anything drawn on top — use mwon12::Overlay.
// It is three lines and it is already handed a bound back buffer.
//
// For replacing the game's shaders with your own HLSL — use the shader kit
// (`shaderkit/README.md`). Set ShaderDump=1 and ShaderMods=1, edit the dumped
// file, restart. No compiler, no C++, and it survives you not being there to
// maintain it. Most "graphics mod" ideas are this, and reaching for the C++ API
// first is the long way round.
//
// This header is for what neither of those can do: reacting to draws as they
// happen, filtering them, injecting a post-process pass, replacing shaders at
// runtime rather than at launch, or capturing the G-buffer.
//
//
// LIFETIME
//
// Attach in OnDeviceCreated, detach in OnDeviceDestroyed. Both matter.
//
// Attaching patches vtable slots on MWOn12's device, command queue and swap
// chain. Detaching restores them. If a plugin is still attached when the device
// is destroyed, the patches point into a DLL that may be about to unload, and
// the process takes an access violation with no stack that names you.
//
// A gfx::Context detaches itself when destroyed, so a plugin that keeps one as
// a member is safe as long as the member does not outlive the plugin. Calling
// Detach() explicitly in OnDeviceDestroyed is still worth doing: it happens at
// the moment the renderer expects, rather than whenever the plugin is freed.
//
//
// THREADING
//
// Callbacks arrive on whichever thread made the D3D12 call, which for this game
// under MWOn12 is the render thread for effectively all of them. They are not
// the same call as OnPresent, though, and VanGFX does not serialise them
// against it: state shared between a draw callback and OnPresent needs its own
// lock.
//
// A callback runs inside the game's frame. Work done there is frame time.

#ifndef MWON12_GRAPHICS_HPP
#define MWON12_GRAPHICS_HPP

#include "mwon12.h"
#include "plugin.hpp"

#include <vangfx/vangfx.hpp>

#include <cstdint>
#include <functional>
#include <memory>
#include <string>
#include <string_view>
#include <utility>

namespace mwon12 {
namespace gfx {

// ── Context ──────────────────────────────────────────────────────────────────

// One VanGFX context attached to MWOn12's renderer.
//
// Moveable, not copyable; detaches itself on destruction. Every VanGFX call is
// reached through operator->, so this adds a lifetime and a log route and gets
// out of the way:
//
//     m_gfx->on_present([](auto&, auto& ev) { ... });
//     auto shader = vangfx::ShaderBuilder{}
//                       .source(hlsl).entry("main").profile("ps_6_0")
//                       .build(*m_gfx);
class Context {
public:
    Context() = default;

    Context(Context&& o) noexcept : m_ctx(std::move(o.m_ctx)) {}

    Context& operator=(Context&& o) noexcept
    {
        if (this != &o) {
            Detach();
            m_ctx = std::move(o.m_ctx);
        }
        return *this;
    }

    Context(const Context&)            = delete;
    Context& operator=(const Context&) = delete;

    ~Context() { Detach(); }

    // Attaches to the device MWOn12 has just created.
    //
    // Everything VanGFX needs is in MWOn12_DeviceInfo, so this is the whole
    // setup. Returns false and logs why on failure; a plugin that gets false
    // should carry on without graphics interception rather than give up, since
    // the usual cause is the DX9 passthrough backend, where there is no D3D12
    // device to attach to and nothing is wrong.
    //
    // `minShaderModel` is in the two-digit form VanGFX uses: 60 for SM 6.0, 66
    // for SM 6.6. Zero, the default, accepts whatever the device offers. Set it
    // if your shaders need a specific model — failing here with a clear message
    // beats failing later inside a compile.
    bool Attach(const MWOn12_DeviceInfo& info,
                uint32_t                 minShaderModel = 0,
                vangfx::LogLevel         logLevel = vangfx::LogLevel::Warn) noexcept
    {
        Detach();

        if (!info.device || !info.commandQueue) {
            LogWarn("gfx: no D3D12 device - nothing to attach to. "
                    "This is the DX9 passthrough backend, not a failure.");
            return false;
        }

        auto built = vangfx::ContextBuilder{}
                         .backend(vangfx::BackendKind::D3D12)
                         .d3d12_device(info.device)
                         .d3d12_command_queue(info.commandQueue)
                         .d3d12_swap_chain(info.swapChain)
                         .d3d12_min_shader_model(minShaderModel)
                         .log_level(logLevel)
                         .log_callback(&Context::Relay)
                         .build();

        if (!built) {
            const auto& msg = built.error().message;
            LogError("gfx: attach failed - %.*s", int(msg.size()), msg.data());
            return false;
        }

        m_ctx = std::move(*built);
        LogInfo("gfx: attached to MWOn12's D3D12 device (SM %u.%u)",
                m_ctx->d3d12_shader_model() / 10,
                m_ctx->d3d12_shader_model() % 10);
        return true;
    }

    // Removes every patch and drops the context. Called by the destructor; safe
    // to call twice, and safe to call when Attach() failed.
    void Detach() noexcept
    {
        if (!m_ctx) return;
        m_ctx.reset();
        LogInfo("gfx: detached");
    }

    [[nodiscard]] bool Attached() const noexcept { return m_ctx != nullptr; }
    explicit operator bool()      const noexcept { return m_ctx != nullptr; }

    // The VanGFX context. Null until Attach() has succeeded -- check Attached()
    // first, or keep every use inside the `if (!m_gfx.Attach(d)) return;` that
    // OnDeviceCreated should start with.
    [[nodiscard]] vangfx::Context* Get()       noexcept { return m_ctx.get(); }
    [[nodiscard]] vangfx::Context* operator->() noexcept { return m_ctx.get(); }
    [[nodiscard]] vangfx::Context& operator*()  noexcept { return *m_ctx; }

private:
    // VanGFX's log, into MWOn12-render.log, tagged with the plugin's name like
    // everything else a plugin writes. Info and below only appear when
    // VerboseLog=1, which is where VanGFX's Debug and Trace levels belong.
    static void Relay(vangfx::LogLevel level, std::string_view msg) noexcept
    {
        switch (level) {
        case vangfx::LogLevel::Error:
            LogError("vangfx: %.*s", int(msg.size()), msg.data()); break;
        case vangfx::LogLevel::Warn:
            LogWarn ("vangfx: %.*s", int(msg.size()), msg.data()); break;
        case vangfx::LogLevel::Info:
            LogInfo ("vangfx: %.*s", int(msg.size()), msg.data()); break;
        default:
            Log(MWON12_LOG_TRACE, "vangfx: %.*s", int(msg.size()), msg.data());
            break;
        }
    }

    std::unique_ptr<vangfx::Context> m_ctx;
};

// ── Shader compilation ───────────────────────────────────────────────────────

// Compiles an HLSL pixel shader from source text.
//
//     auto ps = gfx::CompilePS(m_gfx, R"(
//         float4 main(float4 pos : SV_Position) : SV_Target {
//             return float4(1, 0, 1, 1);
//         })");
//
// Shader model 6.0 through DXC, which is what D3D12 wants and what the profile
// strings in VanGFX's own examples assume. Compile once, at attach time: this
// spawns a compiler, and doing it inside a draw callback costs a visible hitch.
//
// Returns an invalid Shader and logs the compiler's diagnostic on failure --
// the whole diagnostic, because the first line of an HLSL error is rarely the
// one that says what is wrong.
[[nodiscard]] inline vangfx::Shader
CompilePS(Context& ctx, std::string hlsl, std::string entry = "main",
          std::string profile = "ps_6_0") noexcept
{
    if (!ctx) {
        LogError("gfx: CompilePS called before Attach() succeeded");
        return {};
    }

    auto result = vangfx::ShaderBuilder{}
                      .source(std::move(hlsl))
                      .entry(entry)
                      .profile(profile)
                      .build(*ctx);

    if (!result) {
        const auto& msg = result.error().message;
        LogError("gfx: %s (%s) failed to compile - %.*s",
                 entry.c_str(), profile.c_str(),
                 int(msg.size()), msg.data());
        return {};
    }

    LogInfo("gfx: compiled %s (%s), %u bytes",
            entry.c_str(), profile.c_str(),
            unsigned(result->bytecode.size()));
    return std::move(*result);
}

// The same for a vertex shader. Separate rather than a stage argument because
// the profile is the thing that actually differs, and naming it in the call is
// how you notice you passed the wrong one.
[[nodiscard]] inline vangfx::Shader
CompileVS(Context& ctx, std::string hlsl, std::string entry = "main",
          std::string profile = "vs_6_0") noexcept
{
    if (!ctx) {
        LogError("gfx: CompileVS called before Attach() succeeded");
        return {};
    }

    auto result = vangfx::ShaderBuilder{}
                      .source(std::move(hlsl))
                      .entry(entry)
                      .profile(profile)
                      .build(*ctx);

    if (!result) {
        const auto& msg = result.error().message;
        LogError("gfx: %s (%s) failed to compile - %.*s",
                 entry.c_str(), profile.c_str(),
                 int(msg.size()), msg.data());
        return {};
    }

    LogInfo("gfx: compiled %s (%s), %u bytes",
            entry.c_str(), profile.c_str(),
            unsigned(result->bytecode.size()));
    return std::move(*result);
}

// ── Shader replacement ───────────────────────────────────────────────────────
//
// The way to change how the game looks from C++.
//
// D3D12 has no "bind this shader" call: a shader only exists inside a pipeline
// state object, and a PSO is immutable once created. So a shader is replaced at
// the moment MWOn12 builds the PSO, by substituting the bytecode in the
// description before the driver ever sees it.
//
// That is also why VanGFX's own vangfx::replace_ps and vangfx::inject_ps_post
// do nothing here: they work by binding an Effect per draw, which is a D3D9 and
// D3D11 idea. On D3D12 they compile your shader and then never install it.
// These helpers are the path that works.
//
//
// THE WORKFLOW
//
// 1. Log what the renderer builds, and pick one:
//
//        m_gfx->on_pso_create([](auto&, vangfx::d3d12::PSOCreateEvent& ev) {
//            if (ev.kind != vangfx::d3d12::PSOKind::Graphics) return;
//            mwon12::LogInfo("pso: ps %016llX, %u RTs, %u inputs",
//                            mwon12::gfx::BytecodeHash(ev.graphics->ps),
//                            ev.graphics->num_render_targets,
//                            ev.graphics->input_element_count);
//        });
//
// 2. Write a replacement and install it against that hash:
//
//        auto ps = gfx::CompilePS(m_gfx, hlsl);
//        gfx::ReplacePixelShader(m_gfx, ps, gfx::WhenPixelShaderIs(0xA1B2...));
//
// The hash is over the game's translated bytecode, so it is stable for as long
// as MWOn12's translation of that shader is — across runs and across machines,
// but not necessarily across MWOn12 versions. For a mod meant to keep working,
// match on shape (render target count, formats, input layout) rather than on a
// hash, or use the shader kit, whose hashes are of the game's own D3D9 bytecode
// and do not move.
//
//
// THE RULE THAT WILL CATCH YOU
//
// A replacement must be compatible with the root signature the original was
// built against — the same constant buffers, textures and samplers in the same
// registers. MWOn12 built that root signature to match the shader it
// translated, and it is not changed here.
//
// Get it wrong and D3D12 refuses to create the PSO. MWOn12 logs the refusal --
// "[dx12] CreateGraphicsPipelineState failed", with the shader hashes -- and
// the draws that needed that pipeline state do not render, so the symptom is
// something disappearing rather than a crash. Take the registers from the
// shader you are replacing: dump it with ShaderDump=1 and read its
// declarations.

// Identifies which pipeline states a replacement applies to. Return true to
// substitute. Called during PSO creation, which is a load-time event, not a
// per-frame one -- but it is called with the renderer waiting, so keep it cheap.
using PSOMatch = std::function<bool(const vangfx::d3d12::GraphicsPSODesc&)>;

// A stable 64-bit name for a shader blob. FNV-1a; the point is only that the
// same bytecode always produces the same number.
[[nodiscard]] inline uint64_t
BytecodeHash(const vangfx::d3d12::ShaderBytecodeView& blob) noexcept
{
    if (blob.empty()) return 0;

    uint64_t h = 1469598103934665603ull;
    const auto* p = static_cast<const uint8_t*>(blob.data);
    for (size_t i = 0; i < blob.size; ++i) {
        h ^= p[i];
        h *= 1099511628211ull;
    }
    return h;
}

// Matches the one pipeline state whose pixel shader hashes to `hash`.
[[nodiscard]] inline PSOMatch WhenPixelShaderIs(uint64_t hash)
{
    return [hash](const vangfx::d3d12::GraphicsPSODesc& d) {
        return BytecodeHash(d.ps) == hash;
    };
}

// Matches the one pipeline state whose vertex shader hashes to `hash`.
[[nodiscard]] inline PSOMatch WhenVertexShaderIs(uint64_t hash)
{
    return [hash](const vangfx::d3d12::GraphicsPSODesc& d) {
        return BytecodeHash(d.vs) == hash;
    };
}

// Substitutes `replacement` for the pixel shader of every graphics pipeline
// state `match` accepts.
//
// Takes the Shader by value and keeps it alive for as long as the context is
// attached: the bytecode has to still be there when the PSO is created, which
// is not when this is called.
//
// Install during OnDeviceCreated, straight after Attach(). A PSO is created the
// first time the renderer needs it, so anything installed later misses every
// pipeline state built before it -- which, for a shader the game uses in the
// menus, is all of them.
inline void ReplacePixelShader(Context& ctx, vangfx::Shader replacement,
                               PSOMatch match)
{
    if (!ctx) {
        LogError("gfx: ReplacePixelShader called before Attach() succeeded");
        return;
    }
    if (!replacement.valid() || replacement.bytecode.empty()) {
        LogError("gfx: ReplacePixelShader given a shader that failed to compile");
        return;
    }

    auto held = std::make_shared<vangfx::Shader>(std::move(replacement));

    ctx->on_pso_create(
        [held, match = std::move(match)](vangfx::FrameContext&,
                                         vangfx::d3d12::PSOCreateEvent& ev) {
            if (ev.kind != vangfx::d3d12::PSOKind::Graphics || !ev.graphics) return;
            if (!match(*ev.graphics)) return;

            ev.graphics->ps.data = held->bytecode.data();
            ev.graphics->ps.size = held->bytecode.size();

            LogInfo("gfx: pixel shader replaced in one pipeline state "
                    "(%u bytes)", unsigned(held->bytecode.size()));
        });
}

// The same for the vertex shader. Rarely what you want -- changing vertex output
// without changing the pixel shader that consumes it usually just moves geometry
// somewhere it should not be.
inline void ReplaceVertexShader(Context& ctx, vangfx::Shader replacement,
                                PSOMatch match)
{
    if (!ctx) {
        LogError("gfx: ReplaceVertexShader called before Attach() succeeded");
        return;
    }
    if (!replacement.valid() || replacement.bytecode.empty()) {
        LogError("gfx: ReplaceVertexShader given a shader that failed to compile");
        return;
    }

    auto held = std::make_shared<vangfx::Shader>(std::move(replacement));

    ctx->on_pso_create(
        [held, match = std::move(match)](vangfx::FrameContext&,
                                         vangfx::d3d12::PSOCreateEvent& ev) {
            if (ev.kind != vangfx::d3d12::PSOKind::Graphics || !ev.graphics) return;
            if (!match(*ev.graphics)) return;

            ev.graphics->vs.data = held->bytecode.data();
            ev.graphics->vs.size = held->bytecode.size();

            LogInfo("gfx: vertex shader replaced in one pipeline state "
                    "(%u bytes)", unsigned(held->bytecode.size()));
        });
}

}  // namespace gfx
}  // namespace mwon12

#endif  // MWON12_GRAPHICS_HPP
