// SPDX-License-Identifier: MIT
//
// mwsdk/game/mw05_layouts.inl  ***GENERATED - DO NOT EDIT BY HAND***
// =================================================================
// Generated by tools/gen_mw05_layouts.py from the verified Encyclopedia
// datasets (runtime_object_layouts.json). Every value is traceable; nothing is invented.
// Regenerate after any RE-data change. Generated: 2026-07-21 19:37:28Z

#ifndef MWSDK_GAME_MW05_LAYOUTS_INL
#define MWSDK_GAME_MW05_LAYOUTS_INL

#include <cstdint>
#include <string_view>

namespace mwsdk::mw05 {

// A byte offset of a member within a live game object (this+Off).
using Off = std::uint32_t;

// Live C++ object member layouts (Discovery 34, Appendix B.10 + getter/
// behaviour anchors). Named members keep their name; name-stripped getter
// slots are exposed as slot_0xNN. Offsets are from the object base.
namespace layout {
namespace AIActionTraffic { // AIActionTraffic  object 184 B, vtable 0x00891000
inline constexpr Off vtbl_AIAction = 0x0u; // vtbl [verified] AIAction vtable
inline constexpr Off vtbl_ITaskable = 0x4u; // vtbl [verified] ITaskable vtable
inline constexpr Off vtbl_IListener = 0x48u; // vtbl [verified] Sim::Collision::IListener vtable
inline constexpr Off mTargetSpeed = 0x50u; // f32 [verified] target speed m/s (ctor 0x41FE30 seeds 15.646 = 35 mp
inline constexpr Off mSpeedLimit = 0x54u; // f32 [verified] speed limit m/s (ctor seeds 24.587 = 55 mph)
inline constexpr Off mObstacleTarget = 0x5Cu; // ptr [verified] IAvoidable* obstacle (governor braking input)
inline constexpr Off mCrashState = 0xACu; // u32 [verified] crash state (0 none / 1 colliding / 2 disabled)
inline constexpr Off mCrashTimer = 0xB0u; // f32 [verified] crash timer (3.0 s)
inline constexpr Off mRecovery = 0xB4u; // u32 [verified] recovery (0 / 1 realign / 2 resume)
} // AIActionTraffic
namespace AIVehicle { // AIVehicle  object 1852 B, vtable 0x00891998
inline constexpr Off slot_0xC = 0xCu; // u32 [slot] pure-getter slot (AIVehicleCopCar slot 108)
inline constexpr Off slot_0x20 = 0x20u; // u32 [slot] pure-getter slot (shared by 3 AIVehicle*; CopCar slo
inline constexpr Off slot_0x24 = 0x24u; // u32 [slot] pure-getter slot (CopCar slot 25)
inline constexpr Off slot_0x28 = 0x28u; // u32 [slot] pure-getter slot (CopCar slot 26)
inline constexpr Off mDriveSpeed = 0x38u; // f32 [verified] drive speed m/s (SetDriveSpeed 0x431C80; GetDriveSpe
inline constexpr Off slot_0x40 = 0x40u; // u32 [slot] pure-getter slot (CopCar slot 13)
inline constexpr Off slot_0x44 = 0x44u; // u32 [slot] pure-getter slot (CopCar slot 14)
inline constexpr Off slot_0x48 = 0x48u; // u32 [slot] pure-getter slot (CopCar slot 12)
inline constexpr Off slot_0x4C = 0x4Cu; // u32 [slot] pure-getter slot (CopCar slot 29)
inline constexpr Off mTopSpeed = 0x84u; // f32 [verified] top speed m/s (AIVehicleRacecar::GetTopSpeed slot 12
inline constexpr Off mAccelerationTableData = 0x6C4u; // f32[10] [verified] accel-vs-speed curve
inline constexpr Off mAccelerationMaxSpeed = 0x6ECu; // f32 [verified] curve X-max (Table inverseSpacing = 9.0/this)
} // AIVehicle
namespace AICopManager { // AICopManager  object 348 B, vtable 0x008918D8
inline constexpr Off slot_0x50 = 0x50u; // u32 [behavior] pursuit-evasion counter (RecordPursuitEvasion; vtbl+
inline constexpr Off mSpawnRequests = 0x6Cu; // list [verified] pending spawn requests (count +0x70; node 0x44B: pos
inline constexpr Off mSpawnRequestCount = 0x70u; // u32 [verified] count of mSpawnRequests
inline constexpr Off mBreakerZones = 0x78u; // list [verified] breaker zones (count +0x7C; zone 0x1C B: pos+8,expir
inline constexpr Off mBreakerZoneCount = 0x7Cu; // u32 [verified] count of mBreakerZones
inline constexpr Off mVehicles = 0x8Cu; // array [behavior] vehicle array base (OnVehicleAdded/Removed grow/eras
inline constexpr Off mActiveFleet = 0x94u; // u32 [verified] active fleet count (inc on spawn success)
inline constexpr Off mFleetCap = 0x98u; // u32 [verified] fleet cap (UpdatePursuits gates vs this)
inline constexpr Off mSpottedCop = 0xC0u; // ptr [verified] IVehicle* spotted cop (UpdatePatrols->UpdatePursuits
inline constexpr Off mUnitList = 0xC8u; // array [verified] unit list base (count +0xD0)
inline constexpr Off mPursuits = 0xD4u; // list [behavior] pursuit list (StartPursuit scans for local-player ta
inline constexpr Off mRoadblocks = 0x134u; // list [verified] roadblocks (UpdateRoadBlocks 0x439EE0)
inline constexpr Off mDebugRing = 0x13Cu; // ring [verified] 12-B-entry queue (count+0,head+8,cap+0xC; consumer c
} // AICopManager
namespace AITrafficManager { // AITrafficManager  object 948 B, vtable 0x00890F18
inline constexpr Off mSpawnBudgets = 0x64u; // u32[] [verified] per-class spawn budgets (+0x64..0x8C, C17.6)
inline constexpr Off mRoadNav = 0xB4u; // obj [verified] embedded WRoadNav (FindSpawnPoint 0x437DC0 output)
} // AITrafficManager
namespace AIPursuit { // AIPursuit  object 652 B, vtable 0x00892770
inline constexpr Off mActive = 0xA8u; // u32 [behavior] pursuit-active flag (gates OnCopDamaged/OnCopDestroy
inline constexpr Off slot_0xEC = 0xECu; // ptr [behavior] cop ref read on OnCopDestroyed
inline constexpr Off slot_0xF0 = 0xF0u; // ptr [behavior] cop ref read on OnCopDestroyed
inline constexpr Off slot_0xF4 = 0xF4u; // ptr [behavior] cop ref read on OnCopDestroyed
inline constexpr Off slot_0x13C = 0x13Cu; // u32 [behavior] field updated on OnCopDestroyed
inline constexpr Off mCopsDamaged = 0x15Cu; // u32 [behavior] cops-damaged counter (StatTable::IncrementStat 'cops
} // AIPursuit
namespace AICopController { // AICopController
inline constexpr Off mGoalComponent = 0xB8u; // ptr [behavior] goal component sub-object (SetCurrentGoal transition
inline constexpr Off mCurrentGoalHash = 0xC4u; // u32 [behavior] current-goal attrib hash (SetCurrentGoal compares/up
} // AICopController
namespace AIPerpVehicle { // AIPerpVehicle
inline constexpr Off mBustGauge = 0x11Cu; // f32 [behavior] bust gauge vs threshold 5.0 [0x890DA4] -> sets busta
inline constexpr Off mBustMeter = 0x120u; // f32 [behavior] bust meter; +dt*0.25 in-envelope / *4.0 engaged / -d
inline constexpr Off mBustHoldTimer = 0x124u; // f32 [behavior] 3.0 s in-envelope hold -> MPerpBusted
inline constexpr Off mBustableFlag = 0x128u; // u32 [behavior] set to 1 when inside the bust envelope
inline constexpr Off mState = 0x258u; // u32 [behavior] perp state (==3 -> busted, fires MPerpBusted)
} // AIPerpVehicle
namespace LocalPlayer { // LocalPlayer  object 140 B, vtable 0x008B0B10
inline constexpr Off mVehicle = 0x44u; // ptr [behavior] the player's IVehicle* (bound by OnVehicleAdded/Remo
} // LocalPlayer
namespace AIRacerBrain { // AIRacerBrain
inline constexpr Off mSkillScalar = 0x7A8u; // f32 [behavior] catch-up/rubber-band skill scalar (difficulty-indexe
} // AIRacerBrain
namespace Engine { // Engine
inline constexpr Off slot_0x1C = 0x1Cu; // u32 [slot] pure-getter slot (EngineRacer slot 22)
inline constexpr Off slot_0x38 = 0x38u; // u32 [slot] pure-getter slot (EngineDragster slot 33)
inline constexpr Off slot_0x138 = 0x138u; // u32 [slot] pure-getter slot (EngineDragster slot 42)
inline constexpr Off slot_0x13C = 0x13Cu; // u32 [slot] pure-getter slot (EngineDragster slot 43)
} // Engine
namespace EngineTraffic { // EngineTraffic  object 288 B, vtable 0x008AB8F8
inline constexpr Off slot_0x18 = 0x18u; // u32 [slot] pure-getter slot 17 (single-owner)
} // EngineTraffic
namespace Suspension { // Suspension
inline constexpr Off slot_0x98 = 0x98u; // u32 [slot] pure-getter slot (SuspensionSpline slot 75)
inline constexpr Off slot_0xC8 = 0xC8u; // u32 [slot] pure-getter slot (SuspensionSimple slot 63)
} // Suspension
namespace SuspensionRacer { // SuspensionRacer  object 452 B, vtable 0x008ABAC0
inline constexpr Off slot_0xB0 = 0xB0u; // u32 [slot] pure-getter slot 21 (single-owner)
} // SuspensionRacer
namespace SuspensionTraffic { // SuspensionTraffic  object 268 B, vtable 0x008ABB80
inline constexpr Off slot_0xA8 = 0xA8u; // u32 [slot] pure-getter slot 19 (single-owner)
} // SuspensionTraffic
namespace SuspensionTrailer { // SuspensionTrailer  object 260 B, vtable 0x008ABCE0
inline constexpr Off slot_0x94 = 0x94u; // u32 [slot] pure-getter slot 19 (single-owner)
} // SuspensionTrailer
namespace RBTrailer { // RBTrailer  object 404 B, vtable 0x008ACDE0
inline constexpr Off slot_0x44 = 0x44u; // u32 [slot] pure-getter slot 27 (single-owner)
} // RBTrailer
} // namespace layout

namespace layout {
struct MemberInfo { std::string_view cls; std::string_view name; std::string_view type; Off offset; char confidence; };
inline constexpr MemberInfo kMembers[] = {
    {"AIActionTraffic", "__vtbl_AIAction", "vtbl", 0x0u, 'v'},
    {"AIActionTraffic", "__vtbl_ITaskable", "vtbl", 0x4u, 'v'},
    {"AIActionTraffic", "__vtbl_IListener", "vtbl", 0x48u, 'v'},
    {"AIActionTraffic", "mTargetSpeed", "f32", 0x50u, 'v'},
    {"AIActionTraffic", "mSpeedLimit", "f32", 0x54u, 'v'},
    {"AIActionTraffic", "mObstacleTarget", "ptr", 0x5Cu, 'v'},
    {"AIActionTraffic", "mCrashState", "u32", 0xACu, 'v'},
    {"AIActionTraffic", "mCrashTimer", "f32", 0xB0u, 'v'},
    {"AIActionTraffic", "mRecovery", "u32", 0xB4u, 'v'},
    {"AIVehicle", "slot_0xC", "u32", 0xCu, 's'},
    {"AIVehicle", "slot_0x20", "u32", 0x20u, 's'},
    {"AIVehicle", "slot_0x24", "u32", 0x24u, 's'},
    {"AIVehicle", "slot_0x28", "u32", 0x28u, 's'},
    {"AIVehicle", "mDriveSpeed", "f32", 0x38u, 'v'},
    {"AIVehicle", "slot_0x40", "u32", 0x40u, 's'},
    {"AIVehicle", "slot_0x44", "u32", 0x44u, 's'},
    {"AIVehicle", "slot_0x48", "u32", 0x48u, 's'},
    {"AIVehicle", "slot_0x4C", "u32", 0x4Cu, 's'},
    {"AIVehicle", "mTopSpeed", "f32", 0x84u, 'v'},
    {"AIVehicle", "mAccelerationTableData", "f32[10]", 0x6C4u, 'v'},
    {"AIVehicle", "mAccelerationMaxSpeed", "f32", 0x6ECu, 'v'},
    {"AICopManager", "slot_0x50", "u32", 0x50u, 'b'},
    {"AICopManager", "mSpawnRequests", "list", 0x6Cu, 'v'},
    {"AICopManager", "mSpawnRequestCount", "u32", 0x70u, 'v'},
    {"AICopManager", "mBreakerZones", "list", 0x78u, 'v'},
    {"AICopManager", "mBreakerZoneCount", "u32", 0x7Cu, 'v'},
    {"AICopManager", "mVehicles", "array", 0x8Cu, 'b'},
    {"AICopManager", "mActiveFleet", "u32", 0x94u, 'v'},
    {"AICopManager", "mFleetCap", "u32", 0x98u, 'v'},
    {"AICopManager", "mSpottedCop", "ptr", 0xC0u, 'v'},
    {"AICopManager", "mUnitList", "array", 0xC8u, 'v'},
    {"AICopManager", "mPursuits", "list", 0xD4u, 'b'},
    {"AICopManager", "mRoadblocks", "list", 0x134u, 'v'},
    {"AICopManager", "mDebugRing", "ring", 0x13Cu, 'v'},
    {"AITrafficManager", "mSpawnBudgets", "u32[]", 0x64u, 'v'},
    {"AITrafficManager", "mRoadNav", "obj", 0xB4u, 'v'},
    {"AIPursuit", "mActive", "u32", 0xA8u, 'b'},
    {"AIPursuit", "slot_0xEC", "ptr", 0xECu, 'b'},
    {"AIPursuit", "slot_0xF0", "ptr", 0xF0u, 'b'},
    {"AIPursuit", "slot_0xF4", "ptr", 0xF4u, 'b'},
    {"AIPursuit", "slot_0x13C", "u32", 0x13Cu, 'b'},
    {"AIPursuit", "mCopsDamaged", "u32", 0x15Cu, 'b'},
    {"AICopController", "mGoalComponent", "ptr", 0xB8u, 'b'},
    {"AICopController", "mCurrentGoalHash", "u32", 0xC4u, 'b'},
    {"AIPerpVehicle", "mBustGauge", "f32", 0x11Cu, 'b'},
    {"AIPerpVehicle", "mBustMeter", "f32", 0x120u, 'b'},
    {"AIPerpVehicle", "mBustHoldTimer", "f32", 0x124u, 'b'},
    {"AIPerpVehicle", "mBustableFlag", "u32", 0x128u, 'b'},
    {"AIPerpVehicle", "mState", "u32", 0x258u, 'b'},
    {"LocalPlayer", "mVehicle", "ptr", 0x44u, 'b'},
    {"AIRacerBrain", "mSkillScalar", "f32", 0x7A8u, 'b'},
    {"Engine", "slot_0x1C", "u32", 0x1Cu, 's'},
    {"Engine", "slot_0x38", "u32", 0x38u, 's'},
    {"Engine", "slot_0x138", "u32", 0x138u, 's'},
    {"Engine", "slot_0x13C", "u32", 0x13Cu, 's'},
    {"EngineTraffic", "slot_0x18", "u32", 0x18u, 's'},
    {"Suspension", "slot_0x98", "u32", 0x98u, 's'},
    {"Suspension", "slot_0xC8", "u32", 0xC8u, 's'},
    {"SuspensionRacer", "slot_0xB0", "u32", 0xB0u, 's'},
    {"SuspensionTraffic", "slot_0xA8", "u32", 0xA8u, 's'},
    {"SuspensionTrailer", "slot_0x94", "u32", 0x94u, 's'},
    {"RBTrailer", "slot_0x44", "u32", 0x44u, 's'},
};
inline constexpr std::size_t kMemberCount = 62;
} // namespace layout

} // namespace mwsdk::mw05

#endif // MWSDK_GAME_MW05_LAYOUTS_INL
