// SPDX-License-Identifier: MIT
//
// mwsdk/chunk_registry.inl  ***GENERATED FILE - DO NOT EDIT BY HAND***
// =====================================================================
// EAGL chunk-id -> handler table for retail Need for Speed: Most Wanted
// (2005) PC, speed.exe v1.3. Each row is a verified chunk-dispatch entry
// {chunk_id, handler class, LoadChunk VA, UnloadChunk VA, list node VA}.
//
// Generated by tools/gen_chunks.py from chunk_handler_registry.json in
// The Most Wanted Encyclopedia (RE-Data-And-Discoveries). Every VA is
// traceable to that data set; nothing is invented.
// Regenerate after any RE-data change. Generated: 2026-07-20 23:22:07Z

#ifndef MWSDK_CHUNK_REGISTRY_INL
#define MWSDK_CHUNK_REGISTRY_INL

#include <cstdint>
#include <string_view>

namespace mwsdk::chunks {

// One verified chunk-handler dispatch entry. VAs are speed.exe preferred
// addresses (image base 0x00400000); 0 where not recovered.
struct ChunkHandler {
    std::uint32_t    id;         // chunk id (may carry the 0x80000000 container bit)
    std::string_view handler;    // handler class (e.g. "TriggerRegionChunk")
    std::uint32_t    load_va;    // LoadChunk function VA
    std::uint32_t    unload_va;  // UnloadChunk function VA
    std::uint32_t    node_va;    // dispatch list-node VA
};

// Sorted by chunk id (ascending) for binary search.
inline constexpr ChunkHandler kChunks[] = {
    {0x00034027u, "WorldChunk34027", 0x6829D0u, 0x67C040u, 0x92C5FCu},
    {0x00034108u, "ScenerySection", 0x7311F0u, 0x7307E0u, 0x9AA438u},
    {0x00034109u, "WorldChunk34109", 0x728C00u, 0x723D30u, 0x9AA49Cu},
    {0x00034110u, "StreamingSectionTable", 0x72D9A0u, 0x72D9B0u, 0x9AA448u},
    {0x00034111u, "StreamingSectionTable", 0x72D9A0u, 0x72D9B0u, 0x9AA4B4u},
    {0x00034112u, "StreamingSectionTable", 0x72D9A0u, 0x72D9B0u, 0x9AA3F8u},
    {0x00034113u, "StreamingSectionTable", 0x72D9A0u, 0x72D9B0u, 0x9AA3E8u},
    {0x00034146u, "TrackPositionMarkers", 0x7270B0u, 0x727110u, 0x9AA3D8u},
    {0x0003414Du, "TriggerRegionChunk", 0x727670u, 0x723320u, 0x9AA408u},
    {0x00034159u, "WorldChunk34159", 0x74B3A0u, 0x74B3F0u, 0x9B2AACu},
    {0x00034191u, "StreamingBarrierInfo", 0x722480u, 0x7224D0u, 0x9AA3C8u},
    {0x00034201u, "WorldChunk34201", 0x7228B0u, 0x7228E0u, 0x9AB23Cu},
    {0x0003A100u, "EnvelopeTextureChunk", 0x5674D0u, 0x5798C0u, 0x91D498u},
    {0x0003B800u, "WorldMapData", 0x78A120u, 0x767110u, 0x9B3A44u},
    {0x0003B811u, "EventSequencePack", 0x648210u, 0x647D10u, 0x9203E8u},
    {0x0003BB00u, "WorldChunk3BB00", 0x50CC60u, 0x5099C0u, 0x917584u},
    {0x0003BC00u, "WorldChunk3BB00", 0x50CC60u, 0x5099C0u, 0x9160A0u},
    {0x0003BD00u, "WorldChunk3BD00", 0x5042F0u, 0x504330u, 0x9175B0u},
    {0x00135200u, "LightChunks", 0x501A10u, 0x501BF0u, 0x9174B0u},
    {0x8003410Bu, "ScenerySection", 0x7311F0u, 0x7307E0u, 0x9AA418u},
    {0x80034115u, "ScenerySection", 0x7311F0u, 0x7307E0u, 0x9AA428u},
    {0x80034147u, "TriggerRegionChunk", 0x727670u, 0x723320u, 0x9AA468u},
    {0x8003B810u, "EventSequencePack", 0x648210u, 0x647D10u, 0x9203D8u},
    {0x80135000u, "LightChunks", 0x501A10u, 0x501BF0u, 0x9175C0u},
    {0x80135100u, "LightChunks", 0x501A10u, 0x501BF0u, 0x9173D8u},
    {0xB0300100u, "TexturePackChunk", 0x507B50u, 0x507D10u, 0x9173E8u},
    {0xB3300000u, "TexturePackChunk", 0x507B50u, 0x507D10u, 0x9174C0u},
    {0xB3320000u, "TexturePackChunk", 0x507B50u, 0x507D10u, 0x91C180u},
};
inline constexpr std::size_t kChunkCount = 28;

} // namespace mwsdk::chunks

#endif // MWSDK_CHUNK_REGISTRY_INL
